govuk-one-login/authentication-stubs

.github/CODEOWNERS
Currently, both auth and orch approvals are required to merge to this repo - this should not be the case
=> BAU: Fix codeowners file

orchestration-stub/template.yaml
Switch to RP staging perf-test client.
The client in use was not a test client, so the acceptance tests were not able to run.
=> BAU: Switch to RP staging perf-test client

orchestration-stub/src/callback/index.ts, orchestration-stub/src/utils/constants.ts
- Passes sessionId in header to Auth's userinfo endpoint
- This interface was recently updated[1], and the stub now needs to pass this information along to reflect that
[1]- https://github.com/govuk-one-login/authentication-api/commit/4982ca09800e9c751201495c92177145aa0132ce#diff-a02c6800ca638feff17991937c4b9eff5c26039b5c6474a0f5d6a8f02e7c6df5R119
- Code review commit-by-commit
- Ran through and confirmed it works! https://gds.slack.com/archives/C02KUCT0ZAS/p1727096278613759?thread_ts=1727080348.424269&cid=C02KUCT0ZAS
=> BAU: update stub to pass sessionId

.github/workflows/dev-deploy-orch-stub-sp.yaml, orchestration-stub/README.md, orchestration-stub/samconfig.toml, orchestration-stub/template.yaml
Configurations added:
1. authdev1 - SP frontend
2. old-authdev1 - old frontend
3. authdev2 - SP frontend
4. old-authdev2 - old frontend
5. dev - old frontend
6. old-build - old frontend
dev, authdev1 and authdev2 stubs deploy via GitHub workflow and secure pipelines. [SubEnvironment feature](https://govukverify.atlassian.net/wiki/spaces/PLAT/pages/4469489758/Secure+pipelines+support+multiple+dev+environments+within+a+single+AWS+account) added to the template for this purpose. 
old* stubs deploy manually via terminal
Readme updated
=> AUT-3745 - authdev1, authdev2, dev and build accounts stub configurations

orchestration-stub/src/index/index.ts, orchestration-stub/src/services/request-parameters.ts, orchestration-stub/src/types/channel.ts
- Adds a new option to the orch stub, for the `channel` claim
- Validates it is one of three options (none, web, strategic_app)
- Attaches to the JAR payload if you have selected an option which is not none
(90% of this work was already done on the branch https://github.com/govuk-one-login/authentication-stubs/tree/BAU/channel-claim, so thanks @dbes-gds!)
- The auth frontend needs this claim to decide which view to render
=> ATO-1062: Adds channel claim to orch stub JAR 

orchestration-stub/src/index/index.ts
This adds the authenticated claim to the JAR the stub sends to authorize endpoint. This matches the updates made to this interface in orchestration[1] and means any subsequent reliance on this field won't break the stub.
I've not modified the session setup this stub does because I'm unsure if this modifies the frontend session or the shared backend session.
[1]-https://github.com/govuk-one-login/authentication-api/pull/5310/files
=> ATO-980: Adds authenticated claim to JAR

orchestration-stub/src/index/index.ts, orchestration-stub/template.yaml
Fixes an issue when testing reauthentication where the email entered did not match so it was not possible to reauthenticate.
By default rp_sector_host was set to "a.example.com" which caused emails not to match the generated rp pairwise id.
Tested in the dev environment.
- Sets the sector host for each environment to what is in client registry for the client so that the sector host is always the same when generating the id.
- lambdaMemorySize value surrounded by "" to fix local startup failure.
=> BAU: Pass configurable rp_sector_host to auth

ipv-stub/template.yml
The private key has been created manually initially and is being shared via secrets manager for dev environment only.  The key has been created.
To review:
1. Confirm the key has been created correctly.
2. Confirm the key is set in an environment variable for IPV stub lambda.
=> BAU: Add private key for use by the stub to decrypt requests.

ipv-stub/package-lock.json, ipv-stub/package.json, ipv-stub/scripts/encrypt-message-locally.js, ipv-stub/src/endpoints/ipv-authorize.ts, ipv-stub/src/endpoints/render-ipv-authorize.ts, ipv-stub/src/helper/jwt-validator.ts, ipv-stub/src/helper/types.ts, ipv-stub/test/helper/jwt-validator.test.ts, ipv-stub/tsconfig.json
This:
* performs v1 basic validations on the request parameter sent to the ipv stub (for the moment just checking that the `scope` is `reverification`)
* decodes the storage access token stored in the request and performs the same basic validations
* returns a parsed object that can be used in code
This also adds tests, I haven't added the github action to run these tests as there's an existing branch for this, but this to be added soon.
1. Code review
1. Run the tests via `npm run test` while in the ipv stub directory and see that they pass for you
1. Run the ipv stub locally via `npm run build && npm run start:local`. Get a request parameter by also running `npm run encryptSampleRequest`. See that the stub page loads, and that you can see the decoded storage token displayed. Now modify …
=> Aut 3820/validate body

.github/dependabot.yml
All dependabot PRs for eslint and related dependencies are grouped together.
This allows us to reduce the workload managing closely related dependencies.
A previous attempt grouped typescript-eslint packages, whereas this expands the group for all eslint packages we use.
For example these open PRs at the time of drafting:
- https://github.com/govuk-one-login/authentication-stubs/pull/89
- https://github.com/govuk-one-login/authentication-stubs/pull/88
- https://github.com/govuk-one-login/authentication-stubs/pull/87
=> BAU: Group all eslint dependabot PRs

ipv-stub/template.yml
It is for the authorize lambda, so this allows us to distinguish it from others if we follow a pattern like `IPVStubUserInfoLambda`.
=> BAU: Rename `IPVStubLambda` to `IPVStubAuthorizeLambda`

orchestration-stub/template.yaml
[AUT-3690]
Update the orch stub auth frontend url to point to live signin.staging
1. Code Review
[AUT-3690]: https://govukverify.atlassian.net/browse/AUT-3690?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update the orch stub auth frontend url to point to live signin.staging

orchestration-stub/template.yaml
Reverts govuk-one-login/authentication-stubs#106
=> Revert "Update the orch stub auth frontend url to point to live signin.staging"

.github/dependabot.yml
This allows dependency PRs to be available before the working day
We currently use Node 20.17, so no need to get PRs to update types to Node 22.
e.g. we have these PRs:
- https://github.com/govuk-one-login/authentication-stubs/pull/104
- https://github.com/govuk-one-login/authentication-stubs/pull/99
1. Code Review
=> BAU: Improve dependabot scheduling and targeting

ipv-stub/README.md, ipv-stub/package-lock.json, ipv-stub/package.json, ipv-stub/scripts/encrypt-message-locally.mjs, ipv-stub/src/endpoints/ipv-authorize.ts, ipv-stub/src/helper/jwt-validator.ts, ipv-stub/src/helper/types.ts, ipv-stub/src/services/dynamodb-form-response-service.ts, ipv-stub/template.yaml, ipv-stub/test/helper/jwt-validator.test.ts
Adds database for the stub, as well as storing an initial item per request (state for an auth code).
We now generate the auth code, rather than using a hard-coded value. Note, however, that this is not wired together to be the auth code that we return on post - this will come in a subsequent commit + PR. The value of getting this in, for now, is to have a shared database definition to work from.
1. Code Review
1. Run locally and create the database according to the instructions in the README
1. Make a request to the locally running stub using the README instructions
1. See that an item is stored in your local database
1. Deploy to dev (currently deployed) and see that the database is successfully created and written to on mfa reset journey
=> Aut 3861/add dynamo and state storing

README.md, ipv-stub/README.md, ipv-stub/localstack/docker-compose.yaml, ipv-stub/localstack/provision.sh
Add README guidance on how to connect to the localstack DynamoDB database with IntelliJ Database Explorer
Our current localstack implementation is IPV specific, so configuration files and documentation moved to the `ipv-stub` folder.
Part of this was consolidating guidance for creating the local tables, by using docker and adding the Reverification table definition to the provision script.
1. Code Review
2. Follow documentation to get a GUI DynamoDB interface to docker managed DynamoDB instance
=> BAU: Small improvements to localstack DynamoDB management

ipv-stub/src/data/ipv-dummy-constants.ts, ipv-stub/src/endpoints/ipv-authorize.ts, ipv-stub/src/endpoints/render-ipv-authorize.ts, ipv-stub/src/interfaces/reverification-interface.ts, ipv-stub/src/services/dynamodb-form-response-service.ts, ipv-stub/template.yaml
Finishes off some work started in [this PR](https://github.com/govuk-one-login/authentication-stubs/pull/107) to use dynamo to persist things required for the oauth flow.
Specifically, this:
* Adds the auth code as a hidden input to the form rendered on authorize GET to allow it to be used in the POST
* Uses the auth code from the form submitted to authorize POST to retrieve the state and add to the url parameters sent back in the redirect
* Stores the reverification (currently hardcoded) result in authorize POST against the auth code, which sets up data required for the token endpoint and later the user info (or reverification) endpoint.
1. Code Review
1. Run locally. Spin the database up either via localstack or just run locally for now per the PR instructions. See that the flow works …
=> Aut 3681/add more database storing

ipv-stub/src/endpoints/ipv-authorize.ts, ipv-stub/src/endpoints/render-ipv-authorize.ts, ipv-stub/src/services/dynamodb-form-response-service.ts, ipv-stub/template.yaml
Following a chat, we don't actually need to store & retrieve the state in the authorize lambdas, instead we can pass it through the html template and reduce a database call.
1. Code Review
1. Run locally and check all works OK
=> Aut 3681/store less

ipv-stub/localstack/provision.sh
A `Reverification` table is used now, so this is no longer needed
=> BAU: Remove `UserIdentity` table local provisioning

.github/dependabot.yml
They tend to be upgraded with the same releases and grouping them should decrease the time it takes to update them as individual PRs.
For example, at the time of writing these PRs are open:
- https://github.com/govuk-one-login/authentication-stubs/pull/121
- https://github.com/govuk-one-login/authentication-stubs/pull/122
1. Code Review
=> BAU: Group @aws-sdk/* dependabot PRs

.github/dependabot.yml
`ipv-stub` uses `@aws-sdk/*` dependencies, not `orchestration-stub`
=> BAU: Correct `@aws-sdk/*` grouping location

orchestration-stub/template.yaml
staging orchstub redirects to signin.staging domain
Issue: [AUT-3690]
Once deployed to staging, the acceptance tests stage in the new secure pipeline should pass
[AUT-3690]: https://govukverify.atlassian.net/browse/AUT-3690?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AUT-3690: staging orchstub redirects to signin.staging domain

orchestration-stub/template.yaml
Revert "AUT-3690: staging orchstub redirects to signin.staging domain"
This reverts commit ae977886c1dc1e0e629c98c53eed303036326284.
=> Revert "AUT-3690: staging orchstub redirects to signin.staging domain"

orchestration-stub/src/index/index.ts
Recent changes[1] mean that Auth no longer derive the current credential strength from the shared session in uplift helper, but instead rely on a claim passed from orchestration and to auth in the JAR. By adding this claim from the form value we should fix uplift using the orch stub.
[1] - https://github.com/govuk-one-login/authentication-api/pull/5623
=> BAU: Pass credential trust in stub JAR

orchestration-stub/template.yaml
staging sp orchstub redirects to signin.staging domain
Issue: [AUT-3943]
Once deployed to staging, the acceptance tests stage in the new secure pipeline should pass
[AUT-3943]: https://govukverify.atlassian.net/browse/AUT-3943?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AUT-3943: staging orchstub redirects to signin.staging domain

ipv-stub/src/endpoints/render-ipv-authorize.ts
Add a link to the bottom of the IPV stub page to test cross browser
=> AUT-3924: Add link to test cross browser

ipv-stub/src/data/ipv-dummy-constants.ts, ipv-stub/src/endpoints/ipv-authorize.ts, ipv-stub/src/endpoints/render-ipv-authorize.ts, ipv-stub/src/helper/jwt-validator.ts, ipv-stub/src/helper/types.ts, ipv-stub/test/helper/jwt-validator.test.ts
Extend the stub functionality to display the full claim set.  This will allow the redirect_uri to be checked visually and used when re-directing.
1. Code Review
2. Deploy to authdev and check.
=> AUT-3982: IPV Stub Fixes and Improvements for dev environments.

ipv-stub/template.yaml
- The public key has been updated in the authentication API for build.
- The secret has been updated in the secrets manager.
- This commit updates the reference to that of the new secret.
1. Code Review
=> AUT-4064: update ipv private key with new reference

ipv-stub/src/endpoints/ipv-token.ts
- Reverification result sub was being reassigned in the IPV stub to the client sub passed over from ReverificationResultHandler in auth API
- - - The client sub is the same as the issuer in the claims set passed over in the token request in the ReverificationResultHandler in the auth API (example [here](https://bitbucket.org/connect2id/oauth-2.0-sdk-with-openid-connect-extensions/src/master/src/main/java/com/nimbusds/oauth2/sdk/auth/JWTAuthenticationClaimsSet.java))
- This was causing the validation errors in the ReverificationResultHandler as we were expecting a user's sub in the response from the ReverificationResult, not the client sub
1. Code Review
=> BAU: Fix Sub

ipv-stub/template.yaml
Authdev1 for the API was recreated, meaning new keys were created. These have been reflected in Secrets Manager for the stub, and this change ensures we point to the right version.
1. Code Review
=> BAU: Update public key versions for authdev1

orchestration-stub/src/index/index.ts, orchestration-stub/src/services/request-parameters.ts
Orch will be passing new claims to the auth frontend, to replace the need for the client session. Some claims we aim to use are already being passed to the frontend. The new claims are `vtr_list`, `scope`, and `cookie_consent`.
While we will also be passing the google analytics `_ga` parameter, this is optional, so has been left out of the stub.
The form has been updated to allow you to select valid `cookie_consent` values. The other parameters are derived from existing values.
=> ATO-1432: Add new claims to orch stub

orchestration-stub/src/index/index.ts
We're changing the name of the `vtr_list` field to just `vtr`, and changing the format to a string to a list, in orch. This is just reflecting this change in the stub.
Change in orch: https://github.com/govuk-one-login/authentication-api/pull/6224
=> ATO-1435: Rename vtr_lst field to vtr

orchestration-stub/src/index/index.ts
We recently added some new fields to pass to the auth backend, to replace the need for the auth client session. There were some problems with the changes to the orch stub:
- The vtr field was wrapping the `form.confidence` field in double-quotes, which was causing the backend to fail to parse the list. (it was `[\"\"Cl.Cm\"\"]` instead of `[\"Cl.Cm\"]`)
- The client session fields were not the same as the fields being sent to the auth frontend. 
- The `cookie-consent` field was not set on the client session.
I've updated the vtr field to use the correct format, and have updated the client session setup to use the same fields as what we're sending to the auth frontend.
I've deployed this to authdev1 and ran a full auth journey using the new stub changes. The journey completed successfully. …
=> ATO-1435: Fix issues with new client session fields

orchestration-stub/src/index/index.ts
We have changed the claims we are sending from orch to auth frontend. This is updating the stub to reflect these changes.
In short: Instead of `vtr`, we will use `requested_credential_strength`, and since there are no identity journeys in the stub, the `requested_level_of_confidence` is left out of the JAR. 
Note that we would like to get rid of the `confidence` claim we get from orch. In the backend changes, we added another claim called `requested_credential_strength` which we can update the frontend to use. These 2 claims are set to the same value in orch. Once we've swapped to using the new claim with the better name, we can remove the old claim in orch.
For things to not break though, we need to keep sending the `confidence` claim until we remove it from the list of required fields …
=> ATO-1422: Send required claims instead of full vtr list

orchestration-stub/samconfig.toml, orchestration-stub/template.yaml
New Authdev1,2 instances that integrate with the new auth-ext-api.
URLs:
https://orchstub.signin.authdev1.dev.account.gov.uk/
https://orchstub.signin.authdev2.dev.account.gov.uk/
Redefine old account authdev stubs as 'old-' stubs and deployment managed manually via CLI.
New strategic account authdev stubs are deployed via pipeline.
Issues: [AUT-4300], [AUT-4303]
[AUT-4300]: https://govukverify.atlassian.net/browse/AUT-4300?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AUT-4303]: https://govukverify.atlassian.net/browse/AUT-4303?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AUT-4300: New Authdev1,2 orchstub instances that integrate with new auth-ext-api

orchestration-stub/src/index/index.ts
We have stopped sending the `confidence` claim in orch. This is updating the stub to reflect this change.
Have deployed and performed a couple of journeys in authdev. Waiting to test and merge the actual change into orch: https://github.com/govuk-one-login/authentication-api/pull/6508
=> ATO-1650: Stop sending confidence claim in orch stub

orchestration-stub/samconfig.toml, orchestration-stub/template.yaml
Temporary orchstubs that redirect to new SP auth-external-api
Deployed to dev, build and staging
URLs:
https://orchstub-apitest.signin.dev.account.gov.uk/
https://orchstub-apitest.signin.build.account.gov.uk/
https://orchstub-apitest.signin.staging.account.gov.uk/
Deploy using sam CLI
`sam build && sam deploy --config-env {dev/build/staging}-apitest`
Run successful user login journeys using the orchstub urls above
=> AUT-4300: Temporary orchstubs that redirect to new SP auth-external-api

orchestration-stub/src/index/index.ts, orchestration-stub/src/services/request-parameters.ts
Authentication no longer rely on this value being sent from orchestration and instead keep this value is more accurately tracked on the session via Achieved Credential Strength.
We can therefore remove this field
- Code review commit
- Deployed to authdev1 and ran through an uplift journey (Cl + not authenticated) then chose Cl.Cm and authenticated and was prompted for an MFA code
=> ATO-1621: Remove sending current credential strength from stub

orchestration-stub/src/index/index.ts, orchestration-stub/src/services/request-parameters.ts, orchestration-stub/src/types/channel.ts
Rename "mobile" channel to "generic-app" channel. This channel is currently not in use, so is safe to change.
N/A
I have seen that mobile comes on the screen as expected in the original PR. This will also be tested when we test how auth handles this channel.
Original PR: https://github.com/govuk-one-login/authentication-stubs/pull/349
=> AUT-4297: rename mobile channel to generic app channel

orchestration-stub/src/index/index.ts
Adds the claim `subject_type` to the orch stub
Change we are replicating: https://github.com/govuk-one-login/authentication-api/pull/6605
=> ATO-1686: Add subject_type claim to orch stub

orchestration-stub/src/index/index.ts
Adds is_identity_verification_required to orch stub.
https://github.com/govuk-one-login/authentication-api/pull/6655
=> ATO-1607: add is_identity_verification_required to orch stub

orchestration-stub/template.yaml
New feature on orchstub: `accessViaVPNOnly`
When enabled, access is granted via vpn only. A custom 403 message is shown `{"message": "Access denied. Login to VPN"}`.
This is to restrict access to orchstub in higher envs i.e. integration and production envs. 
Hit orchstub url i.e. https://orchstub-apitest.signin.dev.account.gov.uk/
Normal operation when logged in to vpn.
Custom error message response when not in vpn.
=> AUT-4561: Access to orchstub via vpn only
